# Generated by Django 5.0.1 on 2025-05-02 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divulgacion',
            fields=[
                ('id_divultacion', models.AutoField(primary_key=True, serialize=False)),
                ('texto_divulgacion', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('fecha_envio', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PregDS',
            fields=[
                ('id_preg_ds', models.AutoField(primary_key=True, serialize=False)),
                ('preg_ds', models.CharField(max_length=200)),
                ('cod_pregunta_ds', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PregFRM',
            fields=[
                ('id_preg_frm', models.AutoField(primary_key=True, serialize=False)),
                ('preg_frm', models.CharField(max_length=200)),
                ('cod_pregunta_frm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PregFRNM',
            fields=[
                ('id_preg_frnm', models.AutoField(primary_key=True, serialize=False)),
                ('preg_frnm', models.CharField(max_length=200)),
                ('cod_pregunta_frnm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PregTM',
            fields=[
                ('id_preg_tm', models.AutoField(primary_key=True, serialize=False)),
                ('preg_tm', models.CharField(max_length=200)),
                ('cod_pregunta_tm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('cod_provincia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cod provincia')),
                ('nombre_provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('cod_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cod region')),
                ('nombre_region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpcDS',
            fields=[
                ('id_opc_ds', models.AutoField(primary_key=True, serialize=False)),
                ('opc_resp_ds', models.CharField(max_length=200)),
                ('id_preg_ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pregds')),
            ],
        ),
        migrations.CreateModel(
            name='OpcFRM',
            fields=[
                ('id_opc_frm', models.AutoField(primary_key=True, serialize=False)),
                ('opc_resp_frm', models.CharField(max_length=200)),
                ('id_preg_frm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pregfrm')),
            ],
        ),
        migrations.CreateModel(
            name='OpcFRNM',
            fields=[
                ('id_opc_frnm', models.AutoField(primary_key=True, serialize=False)),
                ('opc_resp_frnm', models.CharField(max_length=200)),
                ('id_preg_frnm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pregfrnm')),
            ],
        ),
        migrations.CreateModel(
            name='OpcTM',
            fields=[
                ('id_opc_tm', models.AutoField(primary_key=True, serialize=False)),
                ('opc_resp_tm', models.CharField(max_length=200)),
                ('id_preg_tm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pregtm')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_comuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cod comuna')),
                ('nombre_comuna', models.CharField(max_length=200)),
                ('cod_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='cod_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.region'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_manychat', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Id Manychat')),
                ('rut_usuario', models.IntegerField()),
                ('dv_rut', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('num_whatsapp', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('cod_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='RespTM',
            fields=[
                ('id_resp_tm', models.AutoField(primary_key=True, serialize=False)),
                ('id_manychat', models.CharField(max_length=10)),
                ('fecha_respuesta_tm', models.DateField()),
                ('id_opc_tm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.opctm')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RespFRNM',
            fields=[
                ('id_resp_frnm', models.AutoField(primary_key=True, serialize=False)),
                ('id_manychat', models.CharField(max_length=10)),
                ('fecha_respuesta_frnm', models.DateField()),
                ('id_opc_frnm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.opcfrnm')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RespFRM',
            fields=[
                ('id_resp_frm', models.AutoField(primary_key=True, serialize=False)),
                ('id_manychat', models.CharField(max_length=10)),
                ('fecha_respuesta_frm', models.DateField()),
                ('id_opc_frm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.opcfrm')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RespDS',
            fields=[
                ('id_resp_ds', models.AutoField(primary_key=True, serialize=False)),
                ('id_manychat', models.CharField(max_length=10)),
                ('fecha_respuesta_ds', models.DateField()),
                ('id_opc_ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.opcds')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Perfil')),
                ('telefono', models.IntegerField(default=0)),
                ('cod_acceso', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_sist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTextoPregunta',
            fields=[
                ('id_texto_preg', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('fecha_pregunta_texto', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
    ]
