# Generated by Django 5.0.1 on 2025-05-08 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariotextopregunta',
            old_name='id_usuario',
            new_name='id_manychat',
        ),
        migrations.RemoveField(
            model_name='respds',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='respfrm',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='respfrnm',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='resptm',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='respds',
            name='fecha_respuesta_ds',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='respds',
            name='id_manychat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario'),
        ),
        migrations.AlterField(
            model_name='respfrm',
            name='fecha_respuesta_frm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='respfrm',
            name='id_manychat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario'),
        ),
        migrations.AlterField(
            model_name='respfrnm',
            name='fecha_respuesta_frnm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='respfrnm',
            name='id_manychat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario'),
        ),
        migrations.AlterField(
            model_name='resptm',
            name='fecha_respuesta_tm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resptm',
            name='id_manychat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario'),
        ),
        migrations.AlterField(
            model_name='usuariotextopregunta',
            name='fecha_pregunta_texto',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
