# Generated by Django 5.0.1 on 2025-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_rename_id_usuario_usuariotextopregunta_id_manychat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divulgacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respds',
            name='fecha_respuesta_ds',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respfrm',
            name='fecha_respuesta_frm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respfrnm',
            name='fecha_respuesta_frnm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resptm',
            name='fecha_respuesta_tm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuariotextopregunta',
            name='fecha_pregunta_texto',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
