# Generated by Django 5.0.1 on 2025-05-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_usuario_num_whatsapp'),
        ('usuario', '0002_rename_id_usuario_agenda_id_manychat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divulgacion',
            old_name='id_divultacion',
            new_name='id_divulgacion',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('paciente', 'Paciente')], default='paciente', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cesfam_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.cesfam'),
        ),
    ]
