# Generated by Django 5.0.1 on 2025-05-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_rename_id_divultacion_divulgacion_id_divulgacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario_sist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario'),
        ),
    ]
