# Generated by Django 5.0.1 on 2025-05-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_perfilusuario_cod_acceso'),
        ('usuario', '0003_horaagenda_recordatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDescargaJSON',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('cantidad_horas', models.IntegerField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('cesfam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.cesfam')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
