# Generated by Django 5.0.1 on 2025-05-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_logdescargajson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cod_acceso',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='dv_rut',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rut_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
