# Generated by Django 5.0.1 on 2025-06-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_remove_perfilusuario_cod_acceso_perfilusuario_dv_rut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divulgacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Divulgaciones'},
        ),
        migrations.RemoveField(
            model_name='divulgacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='divulgacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Marcar como inactiva para evitar envíos'),
        ),
        migrations.AddField(
            model_name='divulgacion',
            name='enviada',
            field=models.BooleanField(default=False, help_text='Se marca automáticamente al enviar', verbose_name='¿Enviada?'),
        ),
        migrations.AddField(
            model_name='divulgacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='divulgacion',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='opt_out',
            field=models.BooleanField(default=False, help_text='Si está marcado, el usuario no recibirá mensajes de divulgación', verbose_name='No recibir mensajes'),
        ),
        migrations.AlterField(
            model_name='divulgacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, help_text='Fecha real de envío masivo', null=True),
        ),
        migrations.CreateModel(
            name='LogEnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=False)),
                ('respuesta_api', models.JSONField()),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
                ('divulgacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.divulgacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
            options={
                'verbose_name': 'Log de envío',
                'verbose_name_plural': 'Logs de envíos',
                'indexes': [models.Index(fields=['usuario', 'divulgacion'], name='administrac_usuario_164554_idx')],
            },
        ),
    ]
