# Generated by Django 5.0.1 on 2025-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_alter_divulgacion_options_remove_divulgacion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divulgacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
