# Generated by Django 5.0.1 on 2025-06-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_divulgacion_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_email', models.CharField(max_length=255)),
                ('divulgacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.divulgacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
            options={
                'verbose_name': 'Log de envío',
                'verbose_name_plural': 'Logs de envíos',
            },
        ),
        migrations.DeleteModel(
            name='LogEnvioWhatsApp',
        ),
        migrations.AddIndex(
            model_name='logenvioemail',
            index=models.Index(fields=['usuario', 'divulgacion'], name='administrac_usuario_a99dc1_idx'),
        ),
    ]
