# Generated by Django 5.0.1 on 2025-06-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_logenvioemail_delete_logenviowhatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dv_rut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rut_usuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dv_rut',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_whatsapp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_usuario',
            field=models.TextField(),
        ),
    ]
