# Generated by Django 5.0.1 on 2025-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_logenvioemail_delete_logenviowhatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
    ]
