# Generated by Django 5.0.1 on 2025-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_alter_perfilusuario_dv_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='dv_rut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dv_rut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
