# Generated by Django 5.0.1 on 2025-05-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoFonasa',
            fields=[
                ('cod_fonasa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_prestacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoSnomed',
            fields=[
                ('cod_snomed', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_prestacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cesfam',
            fields=[
                ('id_cesfam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cesfam', models.CharField(max_length=200)),
                ('telefono_cesfam', models.CharField(max_length=15)),
                ('cod_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_procedimiento', models.CharField(max_length=100)),
                ('cod_fonasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.codigofonasa')),
                ('cod_snomed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.codigosnomed')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
                ('requisito_examen', models.CharField(max_length=200)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
                ('id_cesfam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cesfam')),
                ('id_procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.tipoprocedimiento')),
            ],
        ),
    ]
