# Generated by Django 5.0.1 on 2025-05-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='id_usuario',
            new_name='id_manychat',
        ),
    ]
