# Generated by Django 5.0.1 on 2025-05-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_id_usuario_agenda_id_manychat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraAgenda',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada')], max_length=20)),
                ('id_manychat', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario_horas_agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_programada', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.agenda')),
            ],
            options={
                'db_table': 'recordatorios_programados',
            },
        ),
    ]
