name: Enviar Recordatorios

on:
  schedule:
    - cron: '*/15 * * * *'  # Se ejecuta cada 15 minutos

jobs:
  enviar:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar al endpoint de recordatorios
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://tudominio.com/api/recordatorios/enviar/"
