name: Enviar Recordatorios

on:
  schedule:
    - cron: '*/15 * * * *' 
jobs:
  enviar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar solicitud
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.API_TOKEN }}" \ 
            -H "Content-Type: application/json" \
            "https://${{ secrets.PYTHONANYWHERE_USER }}.pythonanywhere.com/API/enviar-recordatorios/"